#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]  # Checking for the 9th iteration (as counting starts from 0)
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
